### ISSUE TITLE
问哈设计逻辑

### ISSUE THREAD

**Issue by lilongcnc** [XHTeng/XHRuntimeDemo#1]
请问哈,在归档解档这一环节,最后把方法封装到了分类'NSObjct+Extension'中,为什么要加上
`- (void)encode:(NSCoder *)aCoder {    
 while (c &&c != [NSObject class]) { 
 xxxxx 
.....
  c = [c superclass];
}`

在while中开始对NSObject做了限制,为什么要开始做这么样的限制呢?我试着去掉了也是可以的,针对继承了NSObjetc的实体类

**Comment by XHTeng** [comment]
这段代码的意思是获取子类的所有属性后再一层层获取父类的所有属性，直到基类NSObject或者superclass为nil

**Comment by lilongcnc** [comment]
明白!多谢!

**Comment by XHTeng** [comment]
close
